coverage:
  paths:
    - coverage/lcov.info

code_to_test_ratio:
  code:
    - lib
  test:
    - test

test_execution_time:
  steps:
    - Run tests with coverage

summary:
  if: true

comment:
  if: is_pull_request

diff:
  if: is_pull_request
  datastores:
    - artifact://${GITHUB_REPOSITORY}

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
