name: matchnotes
description: 'matchnotes is a simple app to manage your matches.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  drift: ^2.28.1
  drift_sqflite: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  collection: ^1.18.0
  syncfusion_flutter_charts: ^31.1.17
  csv: ^6.0.0
  file_picker: ^10.3.2
  wakelock_plus: ^1.2.5
  shared_preferences: ^2.3.2
  media_store_plus: ^0.1.3
  # Firebase core and Crashlytics (version will be resolved by pub)
  firebase_core:
  firebase_crashlytics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
